AWSTemplateFormatVersion: "2010-09-09"
Description: A simple template to create an S3 BucketName
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: just-a-bucket-jaslksdksdjl.com
